version: "3.1"
services:
 nginx:
  image: nginx:alpine
  container_name: my-nginx
  working_dir: /app
  volumes:
   - ./app:/app
   - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
   - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
  ports:
   - "80:80" # HTTP

 php:
  build: docker/php
  container_name: my-php
  working_dir: /app
  volumes:
   # Change directory name to your project name. Example "./app/YOUR_DIRECTORY_NAME:/app"
   - ./app/laravel-swoole-tutorial:/app
   - ./docker/php/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
  ports:
   - "1215:1215" # Swoole port
   # - "9000:9000" # PHP-FPM port
