version: "3.1"
services:

    postgres:
      image: postgres:alpine
      container_name: postgres
      working_dir: /app
      volumes:
        - ./app:/app
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}

    nginx:
      image: nginx:alpine
      container_name: nginx
      working_dir: /app
      volumes:
          - ./app:/app
          - ./mydocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"

    php-fpm:
      build: mydocker/php-fpm
      container_name: php-fpm
      working_dir: /app
      volumes:
        - ./app:/app
        - ./mydocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
